package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"go-stock/backend/data"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/cloudwego/eino/schema"
	"github.com/robfig/cron/v3"
)

const cronScheduleTimezone = "Asia/Shanghai"

// CronScheduleParseRequest describes one AI-assisted schedule parsing request.
// The AI only fills the schedule editor; saving remains a separate user action.
type CronScheduleParseRequest struct {
	Text       string `json:"text"`
	AIConfigID int    `json:"aiConfigId"`
}

// CronScheduleParseResult is the validated, deterministic schedule contract
// returned to the frontend. CronExpr and Summary are generated by this service,
// never trusted from the model output.
type CronScheduleParseResult struct {
	Mode          string `json:"mode"`
	IntervalValue int    `json:"intervalValue,omitempty"`
	IntervalUnit  string `json:"intervalUnit,omitempty"`
	Time          string `json:"time,omitempty"`
	Weekdays      []int  `json:"weekdays,omitempty"`
	MonthDay      int    `json:"monthDay,omitempty"`
	Timezone      string `json:"timezone"`
	Summary       string `json:"summary"`
	CronExpr      string `json:"cronExpr"`
}

type cronScheduleAIOutput struct {
	Mode          string `json:"mode"`
	IntervalValue int    `json:"intervalValue"`
	IntervalUnit  string `json:"intervalUnit"`
	Time          string `json:"time"`
	Weekdays      []int  `json:"weekdays"`
	MonthDay      int    `json:"monthDay"`
}

// ParseCronScheduleText converts natural language into a validated common
// schedule. Ambiguous or unsupported descriptions fail without changing the
// current frontend form.
func ParseCronScheduleText(ctx context.Context, req CronScheduleParseRequest) (*CronScheduleParseResult, error) {
	text := strings.TrimSpace(req.Text)
	if text == "" {
		return nil, fmt.Errorf("请输入希望任务何时执行")
	}
	settings := data.GetSettingConfig()
	if settings == nil || len(settings.AiConfigs) == 0 {
		return nil, fmt.Errorf("尚未配置可用的 AI 模型")
	}
	aiConfig, ok := data.ResolveAIConfig(settings.AiConfigs, req.AIConfigID)
	if !ok || aiConfig == nil {
		if req.AIConfigID > 0 {
			return nil, fmt.Errorf("所选 AI 配置不存在或已被删除")
		}
		return nil, fmt.Errorf("尚未设置默认 AI 模型，请先前往 AI 模型服务配置")
	}

	requestConfig := data.WithSessionThinkingOverride(*aiConfig, false)
	model, err := createChatModel(ctx, requestConfig)
	if err != nil {
		return nil, fmt.Errorf("无法初始化 AI 模型，请检查模型配置")
	}

	systemPrompt := schema.SystemMessage(`你是定时任务执行时间解析器。把用户的中文描述转换为一个 JSON 对象，不要输出 Markdown、解释或额外字段。
仅支持以下四种模式：
1. interval：间隔执行。intervalUnit 只能是 minute、hour 或 day；分钟 1-59，小时 1-23，天 1-31。按天间隔在每天 00:00 按月内日期步进执行。
2. daily：每天固定时间。time 使用 24 小时制 HH:mm。
3. weekly：每周固定时间。weekdays 是整数数组，0=周日，1=周一，...，6=周六；time 使用 HH:mm。
4. monthly：每月固定日期和时间。monthDay 为 1-31；time 使用 HH:mm。

输出字段固定为：mode、intervalValue、intervalUnit、time、weekdays、monthDay。
不适用字段使用零值：数字为 0，字符串为 ""，数组为 []。
“工作日”表示 weekdays=[1,2,3,4,5]。
“中午”只有在用户明确给出具体小时后才能解析；描述含糊、包含多个互不相同的执行时间、秒级规则、交易日历或日期范围时，输出 {"mode":"unsupported","intervalValue":0,"intervalUnit":"","time":"","weekdays":[],"monthDay":0}。
不要自行补充用户没有表达的日期或时间。`)
	userPrompt := schema.UserMessage(text)
	response, err := model.Generate(ctx, []*schema.Message{systemPrompt, userPrompt})
	if err != nil {
		return nil, fmt.Errorf("AI 识别执行时间失败，请稍后重试或手动设置")
	}
	if response == nil || strings.TrimSpace(response.Content) == "" {
		return nil, fmt.Errorf("AI 未返回可用的执行时间")
	}

	var output cronScheduleAIOutput
	if err := json.Unmarshal([]byte(extractJSONObject(response.Content)), &output); err != nil {
		return nil, fmt.Errorf("AI 返回的执行时间格式无法识别，请换一种说法")
	}
	if output.Mode == "unsupported" {
		return nil, fmt.Errorf("这段描述存在歧义或超出常用设置范围，请补充具体时间或使用专家 Cron")
	}

	return normalizeCronSchedule(output)
}

func extractJSONObject(content string) string {
	content = strings.TrimSpace(content)
	start := strings.Index(content, "{")
	end := strings.LastIndex(content, "}")
	if start >= 0 && end > start {
		return content[start : end+1]
	}
	return content
}

func normalizeCronSchedule(output cronScheduleAIOutput) (*CronScheduleParseResult, error) {
	result := &CronScheduleParseResult{
		Mode:     strings.ToLower(strings.TrimSpace(output.Mode)),
		Timezone: cronScheduleTimezone,
	}

	switch result.Mode {
	case "interval":
		unit := strings.ToLower(strings.TrimSpace(output.IntervalUnit))
		if unit != "minute" && unit != "hour" && unit != "day" {
			return nil, fmt.Errorf("AI 未能识别有效的间隔单位")
		}
		maxValue := 59
		unitLabel := "分钟"
		if unit == "hour" {
			maxValue = 23
			unitLabel = "小时"
		} else if unit == "day" {
			maxValue = 31
			unitLabel = "天"
		}
		if output.IntervalValue < 1 || output.IntervalValue > maxValue {
			return nil, fmt.Errorf("执行间隔超出支持范围")
		}
		result.IntervalValue = output.IntervalValue
		result.IntervalUnit = unit
		if unit == "day" {
			// robfig/cron 的日字段按月内日期计算；*/N 跨月后会从新月份重新步进。
			result.CronExpr = fmt.Sprintf("0 0 0 */%d * *", output.IntervalValue)
		} else if unit == "hour" {
			result.CronExpr = fmt.Sprintf("0 0 */%d * * *", output.IntervalValue)
		} else {
			result.CronExpr = fmt.Sprintf("0 */%d * * * *", output.IntervalValue)
		}
		result.Summary = fmt.Sprintf("每 %d %s执行一次", output.IntervalValue, unitLabel)

	case "daily":
		hour, minute, err := parseScheduleTime(output.Time)
		if err != nil {
			return nil, err
		}
		result.Time = formatScheduleTime(hour, minute)
		result.CronExpr = fmt.Sprintf("0 %d %d * * *", minute, hour)
		result.Summary = fmt.Sprintf("每天 %s 执行一次", result.Time)

	case "weekly":
		hour, minute, err := parseScheduleTime(output.Time)
		if err != nil {
			return nil, err
		}
		weekdays, err := normalizeWeekdays(output.Weekdays)
		if err != nil {
			return nil, err
		}
		result.Time = formatScheduleTime(hour, minute)
		result.Weekdays = weekdays
		weekdayValues := make([]string, 0, len(weekdays))
		weekdayLabels := make([]string, 0, len(weekdays))
		for _, weekday := range weekdays {
			weekdayValues = append(weekdayValues, strconv.Itoa(weekday))
			weekdayLabels = append(weekdayLabels, weekdayLabel(weekday))
		}
		result.CronExpr = fmt.Sprintf("0 %d %d * * %s", minute, hour, strings.Join(weekdayValues, ","))
		result.Summary = fmt.Sprintf("每%s %s 执行一次", strings.Join(weekdayLabels, "、"), result.Time)

	case "monthly":
		hour, minute, err := parseScheduleTime(output.Time)
		if err != nil {
			return nil, err
		}
		if output.MonthDay < 1 || output.MonthDay > 31 {
			return nil, fmt.Errorf("每月执行日期必须在 1 到 31 日之间")
		}
		result.Time = formatScheduleTime(hour, minute)
		result.MonthDay = output.MonthDay
		result.CronExpr = fmt.Sprintf("0 %d %d %d * *", minute, hour, output.MonthDay)
		result.Summary = fmt.Sprintf("每月 %d 日 %s 执行一次", output.MonthDay, result.Time)

	default:
		return nil, fmt.Errorf("AI 返回了不支持的执行方式")
	}

	parser := cron.NewParser(cron.Second | cron.Minute | cron.Hour | cron.Dom | cron.Month | cron.Dow)
	if _, err := parser.Parse(result.CronExpr); err != nil {
		return nil, fmt.Errorf("AI 生成的执行规则无效")
	}
	return result, nil
}

func parseScheduleTime(value string) (int, int, error) {
	parsed, err := time.Parse("15:04", strings.TrimSpace(value))
	if err != nil {
		return 0, 0, fmt.Errorf("执行时间必须是 24 小时制 HH:mm")
	}
	return parsed.Hour(), parsed.Minute(), nil
}

func formatScheduleTime(hour, minute int) string {
	return fmt.Sprintf("%02d:%02d", hour, minute)
}

func normalizeWeekdays(values []int) ([]int, error) {
	if len(values) == 0 {
		return nil, fmt.Errorf("每周执行至少需要选择一天")
	}
	seen := make(map[int]struct{}, len(values))
	weekdays := make([]int, 0, len(values))
	for _, value := range values {
		if value < 0 || value > 6 {
			return nil, fmt.Errorf("星期必须在周日到周六之间")
		}
		if _, exists := seen[value]; exists {
			continue
		}
		seen[value] = struct{}{}
		weekdays = append(weekdays, value)
	}
	sort.Ints(weekdays)
	return weekdays, nil
}

func weekdayLabel(value int) string {
	labels := map[int]string{0: "周日", 1: "周一", 2: "周二", 3: "周三", 4: "周四", 5: "周五", 6: "周六"}
	return labels[value]
}
